### ISSUE TITLE
Build fails with "Different types in pointer assignment"

### ISSUE THREAD

**Issue by danielhollas** [Goddard-Fortran-Ecosystem/pFUnit#237]
Hi!

I am trying to incorporate this framework into my Fortran package, but I got stuck in build.
I did the following according to README.md

```sh
mkdir build && cd build
cmake ..
make tests
```
but the last command fails with 
```
/home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/altSet_impl.inc:549.6:
    Included at /home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/map.inc:133:
    Included at /home/hollas/programes/pFUnit/extern/gFTL-shared/src/Integer32Complex128Map.F90:12:

      end_%reference=>this
      1
Error: Different types in pointer assignment at (1); attempted assignment of CLASS(set2) to TYPE(set2)
/home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/altSet_impl.inc:537.6:
    Included at /home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/map.inc:133:
    Included at /home/hollas/programes/pFUnit/extern/gFTL-shared/src/Integer32Complex128Map.F90:12:

      begin%reference=>this
      1
Error: Different types in pointer assignment at (1); attempted assignment of CLASS(set2) to TYPE(set2)
/home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/altSet_impl.inc:164.6:
    Included at /home/hollas/programes/pFUnit/build/extern/gFTL/include/templates/map.inc:133:
    Included at /home/hollas/programes/pFUnit/extern/gFTL-shared/src/Integer32Complex128Map.F90:12:

      find%reference => this
      1
Error: Different types in pointer assignment at (1); attempted assignment of CLASS(set2) to TYPE(set2)
make[3]: *** [extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Integer32Complex128Map.F90.o] Error 1
make[2]: *** [extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/all] Error 2
make[1]: *** [CMakeFiles/tests.dir/rule] Error 2


```

I am using GNU Fortran (GCC) 7.3.0 and CMake 3.13.2. Any help would be highly appreciated. Thanks!

**Comment by tclune** [comment]
At first glance this looks like a compiler problem.   OTOH, I'd have expected to have seen this before as you are unlikely to be the first to try building with 7.3.

Can you capture the output from cmake just to verify which compilers cmake is actually using?     It can sometimes find the system gcc which is generally much older.

Also, do you have access to a more recent gfortran?    I hope this all still works with 7.3, but I honestly have not been using 7.3 in my environments in quite some time.    There may not be a simple workaround here.

**Comment by danielhollas** [comment]
@tclune thanks. Admittedly, CMake is a bit alien to me compared to Make. Could you please advise about how to get the compiler info out of it? When I type `make tests`, I just get this:

```
[  0%] Building C object src/funit/core/CMakeFiles/posix_predefined.x.dir/posix_predefined.c.o
[  0%] Linking C executable posix_predefined.x
[  0%] Built target posix_predefined.x
[  1%] Generating posix_predefined.inc
[  1%] Built target generate_posix_parameters
[  1%] Generating type_template_macros.inc
[  1%] Generating key_template_macros.inc
[  1%] Generating value_template_macros.inc
[  1%] Generating type_template_macros_undefs.inc
[  2%] Generating key_template_macros_undefs.inc
[  2%] Generating value_template_macros_undefs.inc
[  2%] Generating type_testing_macros.inc
[  2%] Generating key_testing_macros.inc
[  3%] Generating value_testing_macros.inc
[  3%] Generating type_set_use_tokens.inc
[  3%] Generating key_set_use_tokens.inc
[  3%] Generating value_set_use_tokens.inc
[  3%] Generating type_use_tokens_undef.inc
[  4%] Generating key_use_tokens_undef.inc
[  4%] Generating value_use_tokens_undef.inc
[  4%] Generating type_macros_undefs.inc
[  4%] Generating key_macros_undefs.inc
[  4%] Generating value_macros_undefs.inc
[  4%] Built target generate-template-incs
[  5%] Generating integer.inc
[  5%] Generating key_integer.inc
[  5%] Generating value_integer.inc
[  5%] Generating real.inc
[  6%] Generating key_real.inc
[  6%] Generating value_real.inc
[  6%] Generating real32.inc
[  6%] Generating key_real32.inc
[  6%] Generating value_real32.inc
[  7%] Generating real64.inc
[  7%] Generating key_real64.inc
[  7%] Generating value_real64.inc
[  7%] Generating complex.inc
[  8%] Generating key_complex.inc
[  8%] Generating value_complex.inc
[  8%] Generating complex64.inc
[  8%] Generating key_complex64.inc
[  8%] Generating value_complex64.inc
[  9%] Generating complex128.inc
[  9%] Generating key_complex128.inc
[  9%] Generating value_complex128.inc
[  9%] Generating logical.inc
[  9%] Generating key_logical.inc
[ 10%] Generating value_logical.inc
[ 10%] Generating character.inc
[ 10%] Generating key_character.inc
[ 10%] Generating value_character.inc
[ 11%] Generating deferredLengthString.inc
[ 11%] Generating key_deferredLengthString.inc
[ 11%] Generating value_deferredLengthString.inc
[ 11%] Generating character17.inc
[ 11%] Generating key_character17.inc
[ 12%] Generating value_character17.inc
[ 12%] Generating unlimitedPoly.inc
[ 12%] Generating key_unlimitedPoly.inc
[ 12%] Generating value_unlimitedPoly.inc
[ 12%] Generating unlimitedPolyPtr.inc
[ 13%] Generating key_unlimitedPolyPtr.inc
[ 13%] Generating value_unlimitedPolyPtr.inc
[ 13%] Generating integer1d.inc
[ 13%] Generating key_integer1d.inc
[ 14%] Generating value_integer1d.inc
[ 14%] Generating integer2d.inc
[ 14%] Generating key_integer2d.inc
[ 14%] Generating value_integer2d.inc
[ 14%] Generating integer2d_fixedExtents.inc
[ 15%] Generating key_integer2d_fixedExtents.inc
[ 15%] Generating value_integer2d_fixedExtents.inc
[ 15%] Generating integerPtr.inc
[ 15%] Generating key_integerPtr.inc
[ 16%] Generating value_integerPtr.inc
[ 16%] Generating integer2dPtr.inc
[ 16%] Generating key_integer2dPtr.inc
[ 16%] Generating value_integer2dPtr.inc
[ 16%] Generating integerAlloc.inc
[ 17%] Generating key_integerAlloc.inc
[ 17%] Generating value_integerAlloc.inc
[ 17%] Generating Foo.inc
[ 17%] Generating key_Foo.inc
[ 17%] Generating value_Foo.inc
[ 18%] Generating FooPtr.inc
[ 18%] Generating key_FooPtr.inc
[ 18%] Generating value_FooPtr.inc
[ 18%] Generating FooPoly.inc
[ 19%] Generating key_FooPoly.inc
[ 19%] Generating value_FooPoly.inc
[ 19%] Generating FooPolyPtr.inc
[ 19%] Generating key_FooPolyPtr.inc
[ 19%] Generating value_FooPolyPtr.inc
[ 19%] Built target generate-type-incs
Scanning dependencies of target gftl-shared
[ 19%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Complex128Vector.F90.o
[ 19%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Complex32Vector.F90.o
[ 20%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Complex64Vector.F90.o
[ 20%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/ComplexVector.F90.o
[ 20%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/DoubleComplexVector.F90.o
[ 20%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Real128Vector.F90.o
[ 21%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Real64Vector.F90.o
[ 21%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/DoubleVector.F90.o
[ 21%] Building Fortran object extern/gFTL-shared/src/CMakeFiles/gftl-shared.dir/Integer32Complex128Map.F90.o
```

**Comment by danielhollas** [comment]
Scratch my last comment. You were right, the cmake indeed seemed to pick up the ancient fortran version. 
This is what helped
```sh
export FC=gfortran
```

Maybe the README.md could be a little more explicit about this. It does mention the FC as a "Setting" which confused me a bit, I did not realize I need to set it as ENV variable. But I should have watched the cmake output more carefully so the jokes on me.

Right now I am hitting a Python encoding issue, but that I can deal with hopefully :crossed_fingers: 

```python
Processing file ../../../tests/funit-core/Test_AssertString.pf
Traceback (most recent call last):
  File "/home/hollas/programes/pFUnit/tests/../bin/funitproc", line 57, in <module>
    main()
  File "/home/hollas/programes/pFUnit/tests/../bin/funitproc", line 50, in main
    processor.run()
  File "/home/hollas/programes/pFUnit/bin/funit/pFUnitParser.py", line 690, in run
    line = self.nextLine()
  File "/home/hollas/programes/pFUnit/bin/funit/pFUnitParser.py", line 705, in nextLine
    line = self.inputFile.readline()
  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2393: ordinal not in range(128)
```

**Comment by danielhollas** [comment]
Okay, making progress. :blush: 

The `tests/funit-core/Test_AssertString.pf` file actually contains a non-ascii quotes character on (commented out) line 184:

https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/9a8e2258e8d81bef5b5e1a9d593299b89ad1c7b7/tests/funit-core/Test_AssertString.pf#L184

Somehow that is screwing up with my Python version. Let me know if you want me to submit a PR for this.

After I deleted the line, the build succeeded, though with one failing test.
```
      Start 11: fhamcrest_tests.x
11/11 Test #11: fhamcrest_tests.x ..........................***Exception: SegFault  0.22 sec
```
The README actually mentions that only GCC versions 8 and up are supported so perhaps this is not surprising with GCC 7.3?

**Comment by tclune** [comment]
Yes - sorry about the assumptions on my part with default CMake behavior.    I learned to use cmake before I properly understood it and had the luxury of working on systems where "FC" was always set to the correct value based upon module load commands.   Mostly this just makes me blind to the issue faced by others, but also complicates verifying the fixes.

Thank you for spotting the bad character - I'm a bit surprised that this was not caught by any of my other compilers - in particular NAG which is usually rather strict about such things.     If you could, yes, please issue a hotfix onto main and I'll roll out a new release.

I had forgotten which of my layers required gfortran 8, so I'm glad you were able to verify in the documentation.      The fhamcrest layer tends to put a lot of stress on the OO capabilities of compilers and I've had to do some awkward workarounds even to get gfortran 10 to compile that section.      One option is to skip fhamcrest entirely.   On the cmake line you could do
```
$ cmake .. -DSKIP_HAMCREST
```
and that entire layer will not be included.   It's a shame though, as assertions in hamcrest are somewhat more elegant.  But for basic testing the "legacy" asserts are quite functional.

**Comment by danielhollas** [comment]
One more note in case somebody else runs into it: 
I had an issue with CMake trying to automatically download the Git submodules. Apparently, my old Git version is not happy with issuing `git submodule` from non-root directory. So I updated submodules manually and then run CMake with 

```sh
cd build && cmake .. -DGIT_SUBMODULE=OFF
```

In any case, I am excited to try this out in our project. @tclune thanks so much for all your work on this! :heart:
